const mockEvents = {
  city: {
    id: 1007700,
    city: 'München',
    lat: 48.14,
    lon: 11.58,
    state: '',
    country: 'de',
    zip: 'meetup3',
    member_count: 1257,
  },
  events: [
    {
      created: 1561546757000,
      duration: 7200000,
      id: '262637434',
      name: '#NoEstimates - How to impr. software development predictability & profitability',
      rsvp_limit: 150,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1573493400000,
      local_date: '2019-11-11',
      local_time: '18:30',
      updated: 1572310315000,
      utc_offset: 3600000,
      waitlist_count: 50,
      yes_rsvp_count: 150,
      venue: {
        id: 25852478,
        name: 'ThoughtWorks Munich ',
        lat: 48.135372,
        lon: 11.613633,
        repinned: true,
        address_1: 'Bothestraße 11',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany',
      },
      group: {
        created: 1413448074000,
        name: 'ThoughtWorks Munich',
        id: 17658472,
        join_mode: 'open',
        lat: 48.14,
        lon: 11.58,
        urlname: 'ThoughtWorks-Muenchen',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/ThoughtWorks-Muenchen/events/262637434/',
      description: '<p>TW hosts: #NoEstimates - How to improve software development predictability and profitability by focusing on what matters</p> <p>In this Meetup, your basic assumptions about the role of estimation will be challenged.</p> <p>',
      how_to_find_us: 'The entrance is right next to the entrance of the big bike shop “Stadler”. If you are standing in front of the entrance of Holiday Inn you have to go around the whole building to find our entrance.',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1564472388000,
      duration: 30600000,
      id: '263577205',
      name: 'Global Day of Coderetreat @ ThoughtWorks Munich',
      rsvp_limit: 70,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1573889400000,
      local_date: '2019-11-16',
      local_time: '08:30',
      rsvp_open_offset: 'PT673H',
      updated: 1564748617000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 69,
      venue: {
        id: 25852478,
        name: 'ThoughtWorks Munich ',
        lat: 48.135372,
        lon: 11.613633,
        repinned: true,
        address_1: 'Bothestraße 11',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany',
      },
      group: {
        created: 1413448074000,
        name: 'ThoughtWorks Munich',
        id: 17658472,
        join_mode: 'open',
        lat: 48.14,
        lon: 11.58,
        urlname: 'ThoughtWorks-Muenchen',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/ThoughtWorks-Muenchen/events/263577205/',
      description: '<p>Welcome to the Global Day of Coderetreat in Munich on Saturday November 16th at ThoughtWorks Munich!</p> <p>On Saturday, November 16th, Coderetreats',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1572344845000,
      duration: 7200000,
      id: '266042622',
      name: 'Technology Radar Vol. 21 Presentation',
      rsvp_limit: 140,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1574877600000,
      local_date: '2019-11-27',
      local_time: '19:00',
      updated: 1573049111000,
      utc_offset: 3600000,
      waitlist_count: 9,
      yes_rsvp_count: 140,
      venue: {
        id: 25852478,
        name: 'ThoughtWorks Munich ',
        lat: 48.13586,
        lon: 11.613354,
        repinned: true,
        address_1: 'Bothestraße 11',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany',
      },
      group: {
        created: 1413448074000,
        name: 'ThoughtWorks Munich',
        id: 17658472,
        join_mode: 'open',
        lat: 48.14,
        lon: 11.58,
        urlname: 'ThoughtWorks-Muenchen',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/ThoughtWorks-Muenchen/events/266042622/',
      description: '<p>*** Registrations via our website ***<br/></p>',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1536494061000,
      duration: 16200000,
      id: 'snxjfqyzpbpb',
      name: 'Meeple Monday',
      rsvp_limit: 20,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1573493400000,
      local_date: '2019-11-11',
      local_time: '18:30',
      rsvp_open_offset: 'PT186H30M',
      rsvp_close_offset: 'PT30M',
      updated: 1536494061000,
      utc_offset: 3600000,
      waitlist_count: 8,
      yes_rsvp_count: 20,
      venue: {
        id: 25689781,
        name: 'Kulturladen Westend',
        lat: 48.134117,
        lon: 11.541716,
        repinned: true,
        address_1: 'Ligsalzstrasse 44',
        city: 'München ',
        country: 'de',
        localized_country_name: 'Germany',
      },
      group: {
        created: 1449524089000,
        name: 'Munich Boardgame Meetup',
        id: 19191650,
        join_mode: 'open',
        lat: 48.14,
        lon: 11.58,
        urlname: 'Munich-Boardgame-Meetup',
        who: 'Boardgamers',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/Munich-Boardgame-Meetup/events/snxjfqyzpbpb/',
      description: '<p>Every second Monday of the month. Location right next to U-Bahn Schwanthalerhöhe. As always: games are usually English or language neutral. There is a fridge with drinks for 1,50 each. Please bring your favorite Games or just join. RSVP opens one week before the event.</p> ',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1536494061000,
      duration: 16200000,
      id: 'snxjfqyzqbmb',
      name: 'Meeple Monday',
      rsvp_limit: 20,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1575912600000,
      local_date: '2019-12-09',
      local_time: '18:30',
      rsvp_open_offset: 'PT186H30M',
      rsvp_close_offset: 'PT30M',
      updated: 1536494061000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 1,
      venue: {
        id: 25689781,
        name: 'Kulturladen Westend',
        lat: 48.134117,
        lon: 11.541716,
        repinned: true,
        address_1: 'Ligsalzstrasse 44',
        city: 'München ',
        country: 'de',
        localized_country_name: 'Germany',
      },
      group: {
        created: 1449524089000,
        name: 'Munich Boardgame Meetup',
        id: 19191650,
        join_mode: 'open',
        lat: 48.14,
        lon: 11.58,
        urlname: 'Munich-Boardgame-Meetup',
        who: 'Boardgamers',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/Munich-Boardgame-Meetup/events/snxjfqyzqbmb/',
      description: '<p>Every second Monday of the month. Location right next to U-Bahn Schwanthalerhöhe. As always: games are usually English or language neutral. There is a fridge with drinks for 1,50 each. Please bring your favorite Games or just join. RSVP opens one week before the event.</p> ',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1572605505000,
      duration: 10800000,
      id: '266131976',
      name: 'Smart Buildings mit Digitale Stadt München e.V.',
      rsvp_limit: 90,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1574874000000,
      local_date: '2019-11-27',
      local_time: '18:00',
      updated: 1572605660000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 75,
      venue: {
        id: 26333376,
        name: 'Isar Valley, Google Germany GmbH',
        lat: 48.14291,
        lon: 11.540947,
        repinned: false,
        address_1: 'Erika-Mann Str. 33',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany',
      },
      group: {
        created: 1328820641000,
        name: 'Internet of Things Munich',
        id: 3265392,
        join_mode: 'open',
        lat: 48.14,
        lon: 11.58,
        urlname: 'IoTMunich',
        who: 'Sensemakers',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/IoTMunich/events/266131976/',
      description: '<p>Wenn Industrie auf Start-up und Tradition auf Innovation',
      how_to_find_us: 'Einfach beim Empfang melden.',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1571209775000,
      duration: 9000000,
      id: '265706638',
      name: 'Evening Workshop on: \'Developing a Coaching Culture in your organisation\'',
      rsvp_limit: 60,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1573752600000,
      local_date: '2019-11-14',
      local_time: '18:30',
      updated: 1573153429000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 59,
      venue: {
        id: 25615449,
        name: 'Henley Business School Germany',
        lat: 48.137886,
        lon: 11.58398,
        repinned: true,
        address_1: 'Maximilianstrasse 40',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany',
      },
      group: {
        created: 1510684582000,
        name: 'Leadership Events - München',
        id: 26598849,
        join_mode: 'open',
        lat: 48.14,
        lon: 11.58,
        urlname: 'Leadership-Events-Munchen',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/Leadership-Events-Munchen/events/265706638/',
      description: '<p>Many organisations are discussing how they can develop a coaching culture. But what does this mean in practice?',
      how_to_find_us: 'Please note: The entrance is along Thomas-Wimmer-Ring in the direction of Isartor, immediately before the intersection with Hildegardstrasse.',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      local_time: '19:00',
      local_date: '2019-11-14',
      link: 'https://www.meetup.com/rice-cookie-improv/events/tjmdkryzpbsb/',
      visibility: 'public_limited',
      group: {
        created: 1468649601000,
        name: 'Rice Cookie Improvtheater in Munich',
        id: 20189476,
        join_mode: 'open',
        lat: 48.14,
        lon: 11.58,
        urlname: 'rice-cookie-improv',
        who: 'Improv-Enthusiasts',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      waitlist_count: 0,
      yes_rsvp_count: 1,
      duration: 7200000,
      time: 1573754400000,
      utc_offset: 3600000,
      name: '¡Improv in Spanish!',
      id: 'tjmdkryzpbsb',
    },
    {
      created: 1573073760000,
      duration: 32400000,
      id: '266267965',
      name: 'Community Day: Cloud Migration, Containers, Kubernetes, and Microservices',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1573722000000,
      local_date: '2019-11-14',
      local_time: '10:00',
      updated: 1573073760000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 8,
      group: {
        created: 1400181332000,
        name: 'Big Data Developers in Munich',
        id: 14476282,
        join_mode: 'open',
        lat: 48.14,
        lon: 11.58,
        urlname: 'Big-Data-Developers-in-Munich',
        who: 'Members',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/Big-Data-Developers-in-Munich/events/266267965/',
      description: '<p>REGISTER HERE FOR THIS FREE EVENT: </p> ',
      visibility: 'public',
      pro_is_email_shared: false,
      member_pay_fee: false,
    },
    {
      created: 1572621679000,
      duration: 10800000,
      id: '266136115',
      name: 'Shut Up & Write!™ Munich',
      rsvp_limit: 12,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1573578000000,
      local_date: '2019-11-12',
      local_time: '18:00',
      rsvp_open_offset: 'PT168H',
      updated: 1573021386000,
      utc_offset: 3600000,
      waitlist_count: 1,
      yes_rsvp_count: 12,
      venue: {
        id: 25711269,
        name: 'Cotidiano Promenadeplatz',
        lat: 48.140083,
        lon: 11.569615,
        repinned: false,
        address_1: 'Maxburgstrasse 4',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany',
      },
      group: {
        created: 1532540208000,
        name: 'Shut Up & Write!® Munich',
        id: 29351354,
        join_mode: 'open',
        lat: 48.14,
        lon: 11.58,
        urlname: 'shutupandwritemunich',
        who: 'Writers',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/shutupandwritemunich/events/266136115/',
      description: '<p>Join us for an hour of writing! ',
      how_to_find_us: 'Look for the Shut up & Write! sign or ask for Stefka',
      visibility: 'public',
      pro_is_email_shared: false,
      member_pay_fee: false,
    },
    {
      created: 1564129835000,
      duration: 7200000,
      id: 'qbmqfryzpbvb',
      name: 'Shut Up & Write!™ Munich',
      rsvp_limit: 15,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1573893000000,
      local_date: '2019-11-16',
      local_time: '09:30',
      rsvp_open_offset: 'PT163H30M',
      updated: 1564129835000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 10,
      venue: {
        id: 25966475,
        name: 'Bellevue München',
        lat: 48.160736,
        lon: 11.563915,
        repinned: false,
        address_1: 'Schleissheimer Str. 142a',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany',
      },
      group: {
        created: 1532540208000,
        name: 'Shut Up & Write!® Munich',
        id: 29351354,
        join_mode: 'open',
        lat: 48.14,
        lon: 11.58,
        urlname: 'shutupandwritemunich',
        who: 'Writers',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/shutupandwritemunich/events/qbmqfryzpbvb/',
      description: '<p>Join us for an hour of writing!  ',
      how_to_find_us: 'Look for the Shut up & Write! sign or ask for Arnaud ',
      visibility: 'public',
      pro_is_email_shared: false,
      member_pay_fee: false,
    },
    {
      created: 1564129835000,
      duration: 7200000,
      id: 'qbmqfryzpbnc',
      name: 'Shut Up & Write!™ Munich',
      rsvp_limit: 15,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1575102600000,
      local_date: '2019-11-30',
      local_time: '09:30',
      rsvp_open_offset: 'PT163H30M',
      updated: 1564129835000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 1,
      venue: {
        id: 25966475,
        name: 'Bellevue München',
        lat: 48.160736,
        lon: 11.563915,
        repinned: false,
        address_1: 'Schleissheimer Str. 142a',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany',
      },
      group: {
        created: 1532540208000,
        name: 'Shut Up & Write!® Munich',
        id: 29351354,
        join_mode: 'open',
        lat: 48.14,
        lon: 11.58,
        urlname: 'shutupandwritemunich',
        who: 'Writers',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/shutupandwritemunich/events/qbmqfryzpbnc/',
      description: '<p>Join us for an hour of writing!  ',
      how_to_find_us: 'Look for the Shut up & Write! sign or ask for Arnaud ',
      visibility: 'public',
      pro_is_email_shared: false,
      member_pay_fee: false,
    },
    {
      created: 1571844132000,
      duration: 10800000,
      id: '265900156',
      name: 'Kanban anhand praktischer Spiele + Open Space',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1573666200000,
      local_date: '2019-11-13',
      local_time: '18:30',
      updated: 1571844132000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 52,
      venue: {
        id: 25772139,
        name: 'it-agile GmbH München',
        lat: 48.150024,
        lon: 11.546462,
        repinned: false,
        address_1: 'Nyphenburgerstrasse 86',
        address_2: '80636',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany',
      },
      group: {
        created: 1520863131000,
        name: 'Kanban Community München - Der alternative Weg zu Agile',
        id: 27806088,
        join_mode: 'open',
        lat: 48.14,
        lon: 11.58,
        urlname: 'Kanban-Community-Munchen',
        who: 'Kanbunnys',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/Kanban-Community-Munchen/events/265900156/',
      description: '<p>Hallo liebe Kanbunnys,</p>  ',
      how_to_find_us: 'Die Büros von it-agile befinden sich im Hinterhof (an Stylight vorbei), Hauseingang ist bei einem Durchgang. Treppenhaus 3. 1. OG.',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1571846604000,
      duration: 7200000,
      id: '265901215',
      name: 'Topic is coming soon',
      rsvp_limit: 60,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1579111200000,
      local_date: '2020-01-15',
      local_time: '19:00',
      rsvp_open_offset: 'PT168H',
      updated: 1571901091000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 5,
      venue: {
        id: 25813875,
        name: 'iteratec GmbH  ',
        lat: 48.119923,
        lon: 11.60281,
        repinned: true,
        address_1: 'St.-Martin-Strasse 114',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany',
      },
      group: {
        created: 1502461506000,
        name: 'Liberating Structures Munich',
        id: 25448417,
        join_mode: 'open',
        lat: 48.14,
        lon: 11.58,
        urlname: 'Liberating-Structures-Munich',
        who: 'Members',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/Liberating-Structures-Munich/events/265901215/',
      description: '<p>Welcome to our first usergroup event for 2020 - and it\'s a GOOD one.</p> <p>As a community of practice, we are all about testing and experimenting with these evolving tools that liberate energy, engagement, and ideas. Come experience these tools with us and we will learn together.</p> <p>Thanks to our host iteratec, we are opening doors at 18:30h with networking over drinks and some food. Our string starts at 19:00h, and goes until about 21:15. ',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1569143472000,
      duration: 7200000,
      id: '265062898',
      name: 'Elementor MeetUp München - Widgets selber erstellen',
      rsvp_limit: 50,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1574186400000,
      local_date: '2019-11-19',
      local_time: '19:00',
      updated: 1573147866000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 21,
      venue: {
        id: 26638286,
        name: 'Heinrich Marketing GmbH',
        lat: 48.14986,
        lon: 11.54947,
        repinned: true,
        address_1: 'Nymphenburger Str. 58',
        address_2: 'Hinterhof, rechts',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany',
      },
      group: {
        created: 1549966106000,
        name: 'Elementor München',
        id: 31146435,
        join_mode: 'open',
        lat: 48.14,
        lon: 11.58,
        urlname: 'Muenchen-Elementor-Meetup',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/Muenchen-Elementor-Meetup/events/265062898/',
      description: '<p>Elementor/Elementor Pro b ',
      how_to_find_us: 'Firma Heinrich Marketing befindet sich im Rückgebäude der Nymphenburger Str. 58, ca. 250 Meter von der U-Bahn-Station Maillinger Str. (U 1) entfernt. Es wird empfohlen, nicht mit dem Auto zu kommen. Freie Parkplätze gibt es in der Umgebung kaum.',
      visibility: 'public',
      pro_is_email_shared: false,
      member_pay_fee: false,
    },
    {
      created: 1572951213000,
      duration: 10800000,
      id: '266227320',
      name: 'Offene Männergruppe | No More Mr Nice Guy',
      rsvp_limit: 24,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1573754400000,
      local_date: '2019-11-14',
      local_time: '19:00',
      updated: 1572951213000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 17,
      venue: {
        id: 26700573,
        name: 'freiraum München ',
        lat: 48.164463,
        lon: 11.561508,
        repinned: false,
        address_1: 'Saarstr. 5',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany',
      },
      group: {
        created: 1440924660000,
        name: 'No More Mr. Nice Guy Männergruppe München',
        id: 18881708,
        join_mode: 'open',
        lat: 48.14,
        lon: 11.58,
        urlname: 'No-More-Mr-Nice-Guy-Muenchen',
        who: 'Männer',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/No-More-Mr-Nice-Guy-Muenchen/events/266227320/',
      description: '',
      how_to_find_us: '1. Stock',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1571223250000,
      duration: 7200000,
      id: '265709123',
      name: 'Best Startups from Hamburg - Pitchnight#1 - München',
      rsvp_limit: 200,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1579111200000,
      local_date: '2020-01-15',
      local_time: '19:00',
      updated: 1571770971000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 35,
      group: {
        created: 1571221326000,
        name: 'Wow Yes Startups - München',
        id: 32898396,
        join_mode: 'open',
        lat: 48.14,
        lon: 11.58,
        urlname: 'wow-yes-Startups-Munchen',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/wow-yes-Startups-Munchen/events/265709123/',
      description: '',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1568278161000,
      duration: 7200000,
      id: '264775795',
      name: 'Entwickle deine Vision für 2020 - mit LEGO SERIOUS PLAY',
      rsvp_limit: 40,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1579024800000,
      local_date: '2020-01-14',
      local_time: '19:00',
      updated: 1569339345000,
      utc_offset: 3600000,
      waitlist_count: 4,
      yes_rsvp_count: 42,
      group: {
        created: 1568114237000,
        name: 'LEGO® SERIOUS PLAY® in München',
        id: 32747384,
        join_mode: 'open',
        lat: 48.14,
        lon: 11.58,
        urlname: 'LEGO-SERIOUS-PLAY-in-Munchen',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/LEGO-SERIOUS-PLAY-in-Munchen/events/264775795/',
      description: '<p>Kreativ ins Jahr 2020 - mit der LEGO SERIOUS PLAY Methode entwickeln wir Visionen, die wir im neuen Jahr umsetzen möchten. Diese können individueller wie berufliche Natur sein, für Einzelpersonen oder Teams. Unkostenbeitrag: 15 Euro. Anmeldung bitte über Eventbrite: </p> ',
      visibility: 'public',
      member_pay_fee: false,
    },
    {
      created: 1571399572000,
      duration: 7200000,
      id: '265768188',
      name: 'Customer Success Makers Meetup - Vol. 8',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1575567000000,
      local_date: '2019-12-05',
      local_time: '18:30',
      updated: 1571399921000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 27,
      group: {
        created: 1491492371000,
        name: 'Customer Success Makers',
        id: 23177193,
        join_mode: 'open',
        lat: 48.14,
        lon: 11.58,
        urlname: 'Customer-Success-Meet-up-Munchen',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin',
      },
      link: 'https://www.meetup.com/Customer-Success-Meet-up-Munchen/events/265768188/',
      description: '<p>More information coming soon - so stay tuned!</p> ',
      visibility: 'public',
      member_pay_fee: false,
    },
  ],
};
export { mockEvents };
